### ISSUE TITLE
Font and Design.

### ISSUE THREAD

**Issue by emjay-engr** [emjay-engr/Open-Source-Group-3#3]
Hindi Visible ang ibang fonts and hndi tugma sa mga design need din baguhin na yong mga text sa html.
@slickim @Aeron-Jay-Tapia @D0cjay @Xiena12 @Aryanjake @janin9 @Cix-prim

**Comment by Aryanjake** [comment]
I suggest na ribayan din ang background design, so mag mamatch sa fonts design para malinig hilingon sa eyes eyes baby hahahah
